<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<xacro: property name="base_length" value="0.6" />
	<xacro: property name="base_width" value="0.4" />
	<xacro: Property name="base_height" value="0.2" />
	<xacro: property name="wheel_radius" value="0.1" />
	<xacro: property name="wheel_length" value="0.05" />
	
	<xacro:macro name="box_inertia" params="mass lx ly lz xyz rpy">
		<inertial> 
			<origin xyz="${xyz}" rpy="${rpy}" />
			<mass value="${mass}" />
			<inertia ixx="${(mass/12.0)*(ly*ly+lz*lz)}" ixy="0" ixz="0"
			iyy="${(mass/12.0)*(lx*lx+lz*lz)}" iyz="0" 
			ixx="${(mass/12.0)*(ly*ly+lx*lx)}" />
		</inertial>
	</xacro:macro>
	
	<xacro:macro name="cylinder_inertia" params="mass radius height xyz rpy">
		<inertial> 
			<origin xyz="${xyz}" rpy="${rpy}" />
			<mass value="${mass}" />
			<inertia ixx="${(mass/12.0)*(3.0*radius*radius+height*height)}" ixy="0" ixz="0"
			iyy="${(mass/12.0)*(3.0*radius*radius+height*height)}" iyz="0" 
			ixx="${(mass/2.0)*(radius*radius)}" />
		</inertial>
	</xacro:macro>
	
	<xacro:macro name="sphere_inertia" params="mass radius xyz rpy">
		<inertial> 
			<origin xyz="${xyz}" rpy="${rpy}" />
			<mass value="${mass}" />
			<inertia ixx="${(mass*.4)*(radius*radius)}" ixy="0" ixz="0" 
			iyy="${(mass*.4)*(radius*radius)}" iyz="0" 
			ixx="${(mass*.4)*(radius*radius)}" />
		</inertial>
	</xacro:macro>
	
	<material name="green">
		<color rgba="0 .6 0 1"/>
	</material>
	
	<material name="white">
		<color rgba="1 1 1 1"/>
	</material>
	
	<material name="gray">
		<color rgba=".7 .7 .7 1"/>
	</material>
	
	<link name="base_link">
		<visual>
			<geometry>
				<box size="${base_length} ${base_width} ${base_height}" />
			</geometry>
			<origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
			<material name="green"/>
		</visual>
		<collision>
			<geometry>
				<box size="${base_length} ${base_width} ${base_height}" />
			</geometry>
			<origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
		</collision>
		<xacro:box_inertia mass="5.0" lx="${base_length}" ly="${base_width}" lz="${base_height}" xyz="0 0 ${base_height/2.0}" rpy="0 0 0" />
	</link>
	
	<link name="lidar">
		<visual>
			<geometry>
				<cylinder radius="${wheel_radius}" length="${wheel_length}" />
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<material name="white"/>
		</visual>
		<collision>
			<geometry>
				<cylinder radius="${wheel_radius}" length="${wheel_length}" />
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</collision>
		<xacro:cylinder_inertia mass="1.0" radius="${wheel_radius}" height="${wheel_length}" xyz="0 0 0" rpy="0 0 0" />
	</link>
	
	<joint name="base_lidar_joint" type="fixed">
		<parent link="base_link"/>
		<child link="lidar"/>
		<origin xyz="${base_length / 4.0} 0 ${base_height + wheel_length / 2.0}" rpy="0 0 0"/>
	</joint>
	
	<link name="left_wheel">
		<visual>
			<geometry>
				<cylinder radius="${wheel_radius}" length="${wheel_length}"/>
			</geometry>
			<origin xyz="0 0 ${wheel_length / 2.0}" rpy="0 0 0"/>
			<material name="gray"/>
		</visual>
		<collision>
			<geometry>
				<cylinder radius="${wheel_radius}" length="${wheel_length}"/>
			</geometry>
			<origin xyz="0 0 ${wheel_length / 2.0}" rpy="0 0 0"/>
		</collision>
		<xacro:cylinder_inertia mass="1.0" radius="${wheel_radius}" height="${wheel_length}" xyz="0 0 ${wheel_length / 2.0}" rpy="0 0 0" />
	</link>
	
	<joint name="base_left_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="left_wheel"/>
		<origin xyz="${-base_length / 4.0} ${base_width / 2.0} 0" rpy="${-pi / 2.0} 0 0"/>
		<axis xyz="0 0 1"/>
	</joint>
	
	<link name="right_wheel">
		<visual>
			<geometry>
				<cylinder radius="${wheel_radius}" length="${wheel_length}"/>
			</geometry>
			<origin xyz="0 0 ${-wheel_length / 2.0}" rpy="0 0 0"/>
			<material name="gray"/>
		</visual>
		<collision>
			<geometry>
				<cylinder radius="${wheel_radius}" length="${wheel_length}"/>
			</geometry>
			<origin xyz="0 0 ${-wheel_length / 2.0}" rpy="0 0 0"/>
		</collision>
		<xacro:cylinder_inertia mass="1.0" radius="${wheel_radius}" height="${wheel_length}" xyz="0 0 ${-wheel_length / 2.0}" rpy="0 0 0" />
	</link>
	
	<joint name="base_right_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="right_wheel"/>
		<origin xyz="${-base_length / 4.0} ${-base_width / 2.0} 0" rpy="${-pi / 2.0} 0 0"/>
		<axis xyz="0 0 1"/>
	</joint>
	
	<link name="caster_wheel">
		<visual>
			<geometry> 
				<sphere radius="${wheel_radius / 2.0}"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<material name="gray"/>
		</visual>
		<collision>
			<geometry> 
				<sphere radius="${wheel_radius / 2.0}"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</collision>
		<xacro:sphere_inertia mass="2.0" radius="${wheel_radius/2.0}"  xyz="0 0 0" rpy="0 0 0" />
	</link>
		
	<joint name="base_caster_wheel_joint" type="fixed">
		<parent link="base_link"/>
		<child link="caster_wheel"/>
		<origin xyz=".2 0 ${-wheel_radius / 2.0}" rpy="0 0 0"/>
	</joint>
	
	<link name="base_footprint"/>
	
	<joint name="base_joint" type="fixed">
		<parent link="base_footprint"/>
		<child link="base_link"/>
		<origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
	</joint> 
		
</robot>
